config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  concern :commentable do
    resources :comments, only: %i[create destroy]
  end

  namespace :api do
    resources :tags, only: :index
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resource :password_reset, only: %i[new create edit update]

    resources :users, only: %i[new create edit update]

    resources :questions, concerns: :commentable do
       resources :answers, except: %i[new show]
    end

    resources :answers, except: %i[new show], concerns: :commentable

    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end

    root 'pages#index'
  end
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Authorship
  include Commentable

  has_many :answers, dependent: :destroy
  belongs_to :user
  
  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags

  validates :title, presence: true, length: { minimum: 2 }
  validates :body, presence: true, length: { minimum: 2 }

  scope :all_by_tags, ->(tag_ids) do
    questions = includes(:user, :question_tags, :tags)
    questions = questions.joins(:tags).where(tags: tag_ids) if tag_ids
    questions.order(created_at: :desc)
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  include ActionView::RecordIdentifier
  include QuestionsAnswers

  before_action :require_authentication, except: %i[show index]
  before_action :set_params, only: %i[edit update destroy show]
  before_action :authorize_question!
  after_action :verify_authorized

  def index
    @pagy, @questions = pagy Question.all_by_tags(params[:tag_ids]), 
      link_extra: 'data-turbo-frame="pagination_pagy"'
    @questions = @questions.decorate
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build question_params

    if @question.save
      respond_to do |format|
        format.html do
      redirect_to questions_path(@question), notice: t('flash.q_create')
        end 
        format.turbo_stream do
          @question = @question.decorate
          flash.now[:notice] = t('flash.q_create')
        end
      end
    else
      render :new
    end
  end

  def update
    if @question.update question_params
      respond_to do |format|
        format.html do
          redirect_to questions_path(anchor: dom_id(@question)), notice: t('flash.q_update')
        end
        format.turbo_stream do
          @question = @question.decorate
          flash.now[:notice] = t('flash.q_update')
       end
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def edit; end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html do
    redirect_to questions_path, status: 303, notice: t('flash.q_delete')
      end

      format.turbo_stream { flash.now[:notice] = t('flash.q_delete')}
    end
  end

  def show
    load_question_answer
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, tag_ids: [])
  end

  def set_params
    @question = Question.find(params[:id])
  end

  # def fetch_tags
  #   @tags = Tag.all
  # end

  def authorize_question!
    authorize(@question || Question)
  end
end

app/views/questions/_form.html.erb
<%= turbo_frame_tag question do %>

  <%= form_with model: question do |f| %>
    <%= render 'shared/errors', object: question%>
    <div class="mb-3 row">
      <div class='col-sm-1 col-form-label text-end'>
        <%= f.label :title%>
      </div>

      <div class="col-sm-10">
        <%= f.text_field :title, placeholder: t('.title'), class: 'form-control'%>
      </div>
    </div>

    <div class="mb-3 row">
      <div class='col-sm-1 col-form-label text-end'>
        <%= f.label :body%>
      </div>

      <div class="col-sm-10">
        <%= f.text_area :body, placeholder: t('.body'), class: 'form-control'%>
      </div>
    </div>

    <div class="mb-3 row">
      <div class="col-sm-1 col-form-label text-end">
        <%= f.label :tags %>
      </div>

      <div class="col-sm-10">
      <%= f.collection_select :tag_ids, question.tags, :id, :title, {}, multiple: true,
          class: 'js-multiple-select', data: {'ajax-url': '/api/tags'} %>
      </div>
    </div>

    <%= f.submit t("global.submit"), class: 'btn btn-primary' %>
    <%= link_to t(".cancel"), questions_path, class: 'btn btn-danger' %>
    <% end %>
<% end %>

app/views/questions/_question.html.erb
 <%= turbo_frame_tag question do %>
 
  <%= tag.article class: "card mt-2", id: dom_id(question) do%>
    
      <section class="card-header">
        <%= question.user.gravatar %>
        <%= question.user.name_or_email%>
      </section>
      
      <div class="card-body">
      <h4><%= link_to question.title, question_path(question),
        data: {turbo_frame: '_top'} %> </h4>

      <section class="card-text">
        <time datetime="<%= question.formatted_created_at %>">
          <small><%= question.formatted_created_at %></small>
        </time>

        <div class="my-2">
          <%= render question.tags %>
        </div>
      
        <p class="my-2">
          <%= sanitize question.body%> 
        </p>
      </section>


          <% if policy(question).edit? %>
            <%= link_to t('global.edit'), edit_question_path(question), class: 'btn btn-secondary'%> 
          <% end %>
        
        
          <% if policy(question).destroy? %>
            <%= link_to t('global.delete'), question_path(question), class: 'btn btn-danger',
              data: {turbo_method: :delete, turbo_confirm: 'Are your sure?'} %>
          <% end %>
      </div>
    <% end %>
  <% end %>

app/views/questions/create.turbo_stream.erb
<%= turbo_stream.prepend 'question', render(@question) %>
<%= prepend_flash %>

app/views/questions/destroy.turbo_stream.erb
<%= turbo_stream.remove @question %>
<%= prepend_flash %>

app/views/questions/edit.html.erb
<% provide :page_title, t('.edit_q')%>
<% currently_at t("menu.quest_s")%>

<h1 class="mb-4"><%= t('.edit_q')%></h1>

<%= render partial: 'form', locals: {question: @question, tags: @tags}%>

app/views/questions/index.html.erb
 <% provide :page_title, t("menu.quest_s")%>
 <% currently_at t("menu.quest_s") %>

<h1 class="mb-4"><%= t("menu.quest_s")%></h1>

<section class="mb-5 ">
  <h2><%= t('.search_by_tags') %></h2>

  <%= form_with url: questions_path, method: :get do |f| %>
    <div class="mb-3">
      <%= f.collection_select :tag_ids, (@tags || []), :id, :title, {selected: params[:tag_ids]},
        multiple: true, required: true,
        class: 'js-multiple-select', data: {'ajax-url': '/api/tags'} %>
    </div>

    <%= f.submit t('global.submit'), class: 'btn btn-primary' %>
  <% end %>
</section>

<div class='mb-2'>
<% if policy(:question).new?%>
  <%= link_to t('.new_question'), new_question_path,
    class: 'btn btn-primary btn-lg', data: { turbo_frame: dom_id(Question.new) }%>
  <div class="my-3">
    <%= turbo_frame_tag Question.new %>
  </div>
<% end %>
</div>

<%= turbo_frame_tag 'pagination_pagy' do %>
  <%= pagination @pagy %>

  <%= turbo_frame_tag 'question' do %>
    <%= render @questions %>
  <% end %>

  <%= pagination @pagy %>
<% end %>

app/views/questions/new.html.erb
<% provide :page_title, t('questions.index.new_question')%>
 <% currently_at t("menu.quest_s") %>

<h1 class="mb-4"><%= t('questions.index.new_question')%></h1>

<%= render partial: 'form', locals: {question: @question, tags: @tags}%>

app/views/questions/show.html.erb
<% provide :page_title, t("menu.quest")%>
 <% currently_at t("menu.quest_s") %>
<article class="mb-3">
  <%= render @question%>
</article>

<%= render 'comments/commentable', commentable: @question, comment: @comment %>
  
<hr class="my-3">

<% if policy(:answer).new? %>
<h2><%= t('.answer_w')%></h2>

<%= render 'answers/form'%>

<h2 class="mt-5"><%= t('.answer')%></h2>
<% end %>

<%= pagination @pagy %> 

<%= turbo_frame_tag 'answers' do %>
  <%= render partial: 'answers/answer', collection: @answers,
   as: :answer, locals: {question: @question} %>
<% end %>

<%= pagination @pagy %>

app/views/questions/update.turbo_stream.erb
<%= turbo_stream.replace @question, render(@question) %>
<%= prepend_flash %>