config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

class AdminConstraint
  def matches?(request)
    user_id = request.session[:user_id] || request.cookie_jar.encrypted[:user_id]

    User.find_by(id: user_id)&.admin_role?
  end
end

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  concern :commentable do
    resources :comments, only: %i[create destroy]
  end

  namespace :api do
    resources :tags, only: :index
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    resource :session, only: %i[new create destroy]

    resource :password_reset, only: %i[new create edit update]

    resources :users, only: %i[new create edit update]

    resources :questions, concerns: :commentable do
       resources :answers, except: %i[new show]
    end

    resources :answers, except: %i[new show], concerns: :commentable

    namespace :admin do
      resources :users, only: %i[index create edit update destroy]
    end

    root 'pages#index'
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Authorship
  include Commentable

  belongs_to :question
  belongs_to :user

  validates :body, presence: true, length: { minimum: 3 }
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include ActionView::RecordIdentifier
  include QuestionsAnswers

  before_action :set_question!
  before_action :set_answer!, except: %i[create]
  before_action :authorize_answer!
  after_action :verify_authorized

  def create
    @answer = @question.answers.build(params_answer_create)

    if @answer.save
      respond_to do |format|
        format.html do
      redirect_to question_path(@question), notice: t('flash.answer_create')
        end
        format.turbo_stream do
          @answer = @answer.decorate
          flash.now[:notice] = t('flash.answer_create')
      end
    end
    else
      load_question_answer(do_render: true)
    end
  end

  def update
    if @answer.update(params_answer_update)
      respond_to do |format|
        format.html do
      redirect_to question_path(@question, anchor: dom_id(@answer)), notice: t('flash.answer_update')
        end
        format.turbo_stream do
          @answer = @answer.decorate
          flash.now[:notice] = t('flash.answer_update')
        end
      end
    else
      render :edit
    end
  end

  def new
    @answer = Answer.new
  end

  def destroy
    @answer.destroy
    respond_to do |format|
      format.html do
    redirect_to question_path(@question), status: 303, notice: t('flash.answer_delete')
      end

      format.turbo_stream {flash.now[:notice] = t('flash.answer_delete')}
    end
  end

  def edit; end

  private

  def params_answer_create
    params.require(:answer).permit(:body).merge(user_id: current_user.id)
  end

  def params_answer_update
    params.require(:answer).permit(:body)
  end

  def set_question!
    @question = Question.find(params[:question_id])
  end

  def set_answer!
    @answer = @question.answers.find(params[:id])
  end

  def authorize_answer!
    authorize(@answer || Answer)
  end
end

app/views/answers/_answer.html.erb
<%= turbo_frame_tag answer do %>
  <%= tag.article class: 'mb-3 card' do %>
    <div class="row g-0">
      <div class="col-sm-auto text-sm-center align-self-center">
        <%= answer.user.gravatar size: 50, css_class: 'd-block' %>
        <%= answer.user.name_or_email%>
      </div>
      <div class="col-sm">
        <div class="card-body">
          <section class="card-text">
            <small><time datetime="<%= answer.formatted_created_at %>">
              <%= answer.formatted_created_at %>
            </time></small>

            <div class="mt-2 mb-3">
              <%= sanitize answer.body%>
            </div>
          </section>

            <% if policy(answer).edit? %>
              <%= link_to t("global.edit"), edit_question_answer_path(question, answer), 
                class: 'btn btn-secondary btn-sm'%> 
            <% end %>

            <% if policy(answer).destroy? %>
              <%= link_to t("global.delete"), question_answer_path(question, answer), 
                class: 'btn btn-danger btn-sm', data: {turbo_method: :delete, turbo_confirm: 'Are your sure?'}%>
            <% end %>
        </div>
      </div>
    <%end%>

    <%= render 'comments/commentable', commentable: answer, comment: @comment %>
<% end %>

app/views/answers/_form.html.erb
<%= turbo_frame_tag @answer do%>

  <%= form_with model: [@question, @answer] do |f| %>
    <%= render 'shared/errors', object: @answer %>

    <div class="mb-3 row">
      <div class='col-sm-1 col-form-label text-end'>
        <%= f.label :body%>
      </div>

      <div class="col-sm-10">
        <%= f.text_area :body, class: 'form-control'%>
      </div>
    </div>

    <%= f.submit t("global.submit"), class: 'btn btn-primary' %>
    <%= link_to t("questions.form.cancel"), question_path(@question), class: 'btn btn-danger'%> 
  <% end %>
<% end %>

app/views/answers/create.turbo_stream.erb
<%= turbo_stream.prepend "answers", render(@answer, question: @answer.question) %>
<%= prepend_flash %>

app/views/answers/destroy.turbo_stream.erb
<%= turbo_stream.remove @answer %>
<%= prepend_flash %>

app/views/answers/edit.html.erb
<% provide :page_title, t('.edit_head')%>
 <% currently_at t("menu.quest_s") %>

<h1 class="mb-4"><%= t(".edit")%> "<%= @question.title%>"</h1>

<%= render 'form'%>

app/views/answers/update.turbo_stream.erb
<%= turbo_stream.replace @answer, render(@answer, question: @answer.question) %>
<%= prepend_flash %>